taskclient/__init__.py,sha256=ZIMf7xr2I9em8TmsyARYJQQbmjwpcS7vNfp8gS2RG5Y,1301
taskclient/connection.py,sha256=jQQcnr-RrxdV4AjcMeEAMjEfWCsak2YWgILu7O57ZOM,17616
taskclient/drivers.py,sha256=dpMu7IFYcvYEHdAx3xsnEFYq_l60OlnLwyNMpPcbU9A,944
taskclient/exceptions.py,sha256=hq7LmKV3Uq5FdcSg3Vh7UysCqvJffxG7mSorY-6Wnus,904
task_client-0.1.0.dist-info/LICENSE,sha256=ohsbe-1180tqV0K-E81i4S5MMEHucR1lLirw3LvIpXw,665
task_client-0.1.0.dist-info/METADATA,sha256=OhAygelNtOGGVNNbSDam-1_O-mBDc6qJrdhqC5OdRyI,1351
task_client-0.1.0.dist-info/WHEEL,sha256=g4nMs7d-Xl9-xC9XovUrsDHGXt-FT0E17Yqo92DEfvY,92
task_client-0.1.0.dist-info/entry_points.txt,sha256=eqGnTHtEVMYwfXVk1Z9MhC8O2N8wuqAbr0lisLmrkxs,20
task_client-0.1.0.dist-info/top_level.txt,sha256=iW8O438sdBiWDCHlB0DFKW5ZOtxdKmvcA2_NuCDuUaA,11
task_client-0.1.0.dist-info/RECORD,,
